version: '3.4'

services:
  db:
    image: postgres:latest
    restart: always
    container_name: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345678
      POSTGRES_DB: Gimji
    ports:
      - "5432:5432"
  gimji:
    image: ${DOCKER_REGISTRY-}gimji
    build:  
      context: .
      dockerfile: Gimji/Dockerfile
    ports:  
      - "5000:80"
    depends_on:
      - db
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=Gimji;Username=postgres;Password=12345678 
    volumes:
      - E:\Classroom\C#\CNDOTNET_BACKEND\Gimji\Gimji:/app
